# Generated by Django 3.2.4 on 2021-07-04 07:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=250)),
                ('emp_id', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_role', models.CharField(choices=[('hr', 'HR'), ('developer', 'Developer'), ('tester', 'Tester'), ('manager', 'Manager')], max_length=250)),
                ('emp_salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('emp_joinied_date', models.DateField(default=datetime.date(2021, 7, 4))),
                ('emp_education', models.CharField(max_length=250)),
                ('emp_age', models.IntegerField()),
                ('emp_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=250)),
                ('emp_contact', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
