# Generated by Django 3.2.4 on 2021-07-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_emp_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=250),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_role',
            field=models.CharField(choices=[('HR', 'hr'), ('Developer', 'developer'), ('Tester', 'tester'), ('Manager', 'manager')], max_length=250),
        ),
    ]
