# Generated by Django 3.2.4 on 2021-07-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('employee', 'Employee')], max_length=250, null=True),
        ),
    ]
